set nonumber
set autoread
set splitbelow
set splitright

runtime! ftplugin/man.vim

call plug#begin()

Plug 'tpope/vim-sensible'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'dracula/vim'

call plug#end()

let g:coc_global_extensions = [
  \'coc-json'
  \,'coc-yaml'
  \,'coc-git'
  \,'coc-clangd'
  \,'coc-explorer'
\]

colorscheme dracula

let mapleader = "t"
command! ReloadVimrc source $MYVIMRC
nnoremap <silent> <Plug>ReloadVimrc :ReloadVimrc <enter>
nnoremap <leader>r <Plug> ReloadVimrc

command! EditVimrc split $MYVIMRC
nnoremap <silent> <Plug>EditVimrc :EditVimrc <enter>
nnoremap <leader>e <Plug>EditVimrc

nnoremap <leader>ce :CocConfig <enter>
nnoremap <leader>cr :CocRestart <enter>


