set nonumber
set autoread

runtime! ftplugin/man.vim

call plug#begin()

Plug 'tpope/vim-sensible'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'dracula/vim'

call plug#end()

let g:coc_global_extensions = [
  \'coc-json'
  \,'coc-yaml'
  \,'coc-git'
  \,'coc-clangd'
\]

colorscheme dracula
