
shell = "/usr/local/bin/nu"
working_directory = "None"
live_config_reload = true
ipc_socket = false
[window]
dimensions = { columns = 0, lines = 0 }
position = "None"
padding = { x = 0, y = 0 }
dynamic_padding = true
decorations = "None"
opacity = 1.0
blur = false
title = ""
dynamic_title = true
decorations_theme_variant = "None"

[scrolling]
history = 100000
multiplier = 3

[font]
normal = { family = "DepartureMono", style = "Regular" }
size = 11.25

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true
