[terminal]
shell = "/usr/local/bin/nu"

[general]
live_config_reload = true
ipc_socket = false

[window]
dimensions = { columns = 0, lines = 0 }
position = "None"
padding = { x = 10, y = 5 }
dynamic_padding = true
decorations = "Full"
opacity = 1.0
blur = false
title = ""
dynamic_title = true
decorations_theme_variant = "None"

[scrolling]
history = 100000
multiplier = 3

[font]
normal = { family = "Cousine for Powerline", style = "Regular" }
bold = { family = "Fira Mono for Powerline", style = "Bold" }
italic = { family = "Meslo LG M DZ for Powerline", style = "Italic" }
size = 11.2

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

[cursor]
style = "Block"
